version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-frontend
    networks:
      - resume-network
    ports:
      - "3000:4800"

networks:
  resume-network:
    external: true